// front/src/pages/Home.vue
<template>
     <Navbar />
    <Hero />
    <Banner />
    <TopSellers />
    <Teachers />
    <Faq />
    <Partners />
    <Footer />
</template>

<script setup>
import Navbar from '../components/Navbar.vue'
import Hero from '../components/Hero.vue'
import Partners from '../components/Partners.vue'
import TopSellers from '../components/TopSellers.vue'
import Footer from '../components/Footer.vue'
import Banner from '../components/Banner.vue'
import Faq from '../components/Faq.vue'
import Teachers from '../components/Teachers.vue'
</script>

// client/src/pages/Home.jsx
import React from 'react'
import Navbar from '../components/Navbar.vue'
import Hero from '../components/Hero.vue'
import Partners from '../components/Partners.vue'
import TopSellers from '../components/TopSellers.vue'
import Footer from '../components/Footer.vue'
import Banner from '../components/Banner.vue'
import Faq from '../components/Faq.vue'
import Teachers from '../components/Teachers.vue'
const Home = () => {
  return (
   <>
    <Navbar />
    <Hero />
    <Banner />
    <TopSellers />
    <Teachers />
    <Faq />
    <Partners />
    <Footer />
   </>
  )
}

export default Home
